name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

    sonar:
      uses: ./.github/workflows/validate.yml
